### ISSUE TITLE
I got this issue how to fix it

### ISSUE THREAD

**Issue by Rustbreaker17** [DraGo0oN/Pterodactyl-VPS-Egg#3]
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from ydrag0n/pterodactyl-vps-egg 
Status: Image is up to date for quay.io/ydrag0n/pterodactyl-vps-egg:latest 
Digest: sha256:71576d29d8dc1b60124d28ed6269359deb8c2fd6571f9cd5d00076b1fd108139 
[Pterodactyl Daemon]: Finished pulling Docker container image
exec /bin/bash: exec format error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by BasToTheMax** [comment]
You're using an ARM cpu, probably from Oracle Cloud free tier... 💀

At the moment, only AMD is supported. Or you could rebuild the image on your vps to let it work, but that required knowledge of Linux and docker.

**Comment by DraGo0oN** [comment]
As I mentioned, AMD and Intel CPUs are supported, which means any x86 CPU can be used to run this vps image.
