### ISSUE TITLE
How to log in as root?

### ISSUE THREAD

**Issue by shunya725** [DraGo0oN/Pterodactyl-VPS-Egg#4]
How to log in as root?
sudo su - didn't work

**Comment by DraGo0oN** [comment]
Currently not working

**Comment by BasToTheMax** [comment]
Just use sudo

**Comment by shunya725** [comment]
sudo cannot be used.
I get an error

**Comment by BasToTheMax** [comment]
What error are you getting?

**Comment by weeaudi** [comment]
The issue is with the fact that pterodactyl has the "no new privileges" flag set. meaning that sudo is not accessable without disabling this flag. how you do that i don't know
